projekt_zespolowy/cardeals/urls.py
from django.urls import path
from cardeals.views import (
    CarDealListView,
    CarCreateView,
    CarDealCreateView,
    CarDealDetailView,
    CarDealUpdateView,
    CarDealDeleteView,
    DashboardView,
)

app_name = 'cardeals'
urlpatterns = [
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path('', CarDealListView.as_view(), name='list'),
    path("createcar/", CarCreateView.as_view(), name='createcar'),
    path("createcardeal/", CarDealCreateView.as_view(), name='createcardeal'),
    path("<str:slug>/", CarDealDetailView.as_view(), name='detail'),
    path("<str:slug>/edit/", CarDealUpdateView.as_view(), name='editcardeal'),
    path("<str:slug>/delete/", CarDealDeleteView.as_view(), name='deletecardeal'),
]

projekt_zespolowy/config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView, RedirectView
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    #path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("projekt_zespolowy.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("",RedirectView.as_view(
        query_string=True,
        pattern_name="cardeals:list"),
         name="home"),
    path("cardeals/", include("cardeals.urls", namespace="cardeals")),
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("api/auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

projekt_zespolowy/cardeals/models.py
from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext as _

from datetime import datetime

from projekt_zespolowy.users.models import User
from cardeals.utils import generate_slug

class Car(models.Model):
    """User car model class"""
    class ConditionChoice(models.TextChoices):
        NEW = "N", _("New")
        USED = "U", _("Used")
        CERTIFIED = "C", _("Certified Pre-Owned")
        TOTALED = "T", _("Totaled")
    class FuelChoice(models.TextChoices):
        PETROL = "P", _("Petrol")
        DIESEL = "D", _("Diesel")
        ELECTRIC = "E", _("Electric")
        HYBRID = "H", _("Hybrid")
        PLUG_IN_HYBRID = "PL", _("Plug-In Hybrid")
        CNG = "C", _("CNG")
        LPG = "L", _("LPG")
        HYDROGEN = "HY", _("Hydrogen")
        ETHANOL = "ET", _("Ethanol")
    class TransmissionChoice(models.TextChoices):
        MANUAL = "M", _("Manual")
        AUTOMATIC = "A", _("Automatic")
        CVT = "C", _("CVT")
        DUAL_CLUTCH = "D", _("Dual Clutch")
        SEMI_AUTOMATIC = "S", _("Semi-Automatic")
    class DriveTypeChoice(models.TextChoices):
        FRONT = "FR", _("Front (FWD)")
        REAR = "R", _("Rear (RWD)")
        ALL = "A", _("All (AWD)")
        FOUR = "F", _("Four (FWD)")
    slug = models.SlugField(max_length=256, unique=True, editable=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, verbose_name='Author')
    manufacturer = models.CharField(max_length=50, verbose_name='Car Manufacturer')
    model = models.CharField(max_length=50, verbose_name='Car Model')
    version = models.CharField(max_length=50, verbose_name='Car Version')
    odometer = models.PositiveIntegerField(default=0, help_text="Mileage", verbose_name='Car Odometer')
    colour = models.CharField(max_length=20, verbose_name='Car Colour')
    number_of_doors = models.PositiveSmallIntegerField(default=5, verbose_name='Car Number of Doors')
    number_of_seats = models.PositiveSmallIntegerField(default=5, verbose_name='Car Number of Seats')
    engine_displacement = models.PositiveIntegerField(help_text="Engine displacement in cubic centimeters (cc)", verbose_name='Car Engine Displacement')
    power = models.PositiveIntegerField(help_text="Engine power in horsepower (hp)", verbose_name='Car Power')
    year = models.PositiveSmallIntegerField(verbose_name='Car Year',
                                                validators=[MinValueValidator(1886), MaxValueValidator(datetime.now().year)])
    condition = models.CharField(max_length=20, choices=ConditionChoice, default=ConditionChoice.USED, verbose_name='Car Condition')
    fuel_type = models.CharField(max_length=20, choices=FuelChoice, default=FuelChoice.PETROL, verbose_name='Car Fuel Type')
    transmission_type = models.CharField(max_length=20, choices=TransmissionChoice, default=TransmissionChoice.MANUAL, verbose_name='Car Transmission Type')
    drive_type = models.CharField(max_length=20, choices=DriveTypeChoice, default=DriveTypeChoice.FRONT, verbose_name='Car Drive Type')

    def save(self, *args, **kwargs):
        if not self.slug:
            base = (self.manufacturer+" "+self.model+" "+self.version).strip()
            for candidate in generate_slug(base):
                if not CarDeal.objects.filter(slug=candidate).exists():
                    self.slug = candidate
                    break
            else:
                raise Exception("Can't create new Car object")

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("cardeals:list")

    def __str__(self):
        return self.manufacturer+" "+self.model+" "+self.version


class CarDeal(models.Model):
    """User car deal model class"""
    car = models.ForeignKey(Car, on_delete=models.CASCADE, blank=False, verbose_name='Car', related_name='deals')
    title = models.CharField(max_length=150, verbose_name=_('Title'))
    slug = models.SlugField(max_length=256, unique=True, editable=False)
    description = models.TextField(default=_("No description available."), blank=True, verbose_name=_("Description"))
    main_photo = models.URLField(verbose_name="Photo", null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, verbose_name='Author')
    price = models.DecimalField(max_digits=12, decimal_places=2, verbose_name='Price')
    contact = models.CharField(max_length=15, verbose_name=_('Contact'),
                               validators=[RegexValidator(regex=r'^\+?\d{1,4}?[-.\s]??\(?\d{1,3}?\)?[-.\s]??\d{1,4}[-.\s]??\d{1,4}[-.\s]??\d{1,9}$',
                                                          message="Enter a valid phone number.")])

    def save(self, *args, **kwargs):
        if not self.slug:
            base = self.title.strip()
            for candidate in generate_slug(base):
                if not CarDeal.objects.filter(slug=candidate).exists():
                    self.slug = candidate
                    break
            else:
                raise Exception("Can't create new CarDeal object")

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("cardeals:detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.title

projekt_zespolowy/cardeals/forms.py
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.forms import ModelForm, HiddenInput
from cardeals.models import Car, CarDeal
from projekt_zespolowy.users.models import User

class CarForm(ModelForm):
    def __init__(self, *args, **kwargs):
        """Make sure car author is currently logged-in user."""
        self.request = kwargs.pop('request')
        super(CarForm, self).__init__(*args, **kwargs)
        self.fields['author'].queryset = User.objects.filter(id=self.request.user.id)
        self.fields['author'].initial = User.objects.get(id=self.request.user.id)
        self.fields['author'].widget = HiddenInput()
    class Meta:
        model = Car
        fields = '__all__'

class CarDealForm(ModelForm):
    def __init__(self, *args, **kwargs):
        """Make sure car deal author is currently logged-in user."""
        self.request = kwargs.pop('request')
        super(CarDealForm, self).__init__(*args, **kwargs)

        """Check if the currently logged-in user has authored cars"""
        user_cars = Car.objects.filter(author=self.request.user.id)
        if not user_cars.exists():
            messages.info(self.request, 'You have not authored any cars! Create your car first.')
            #TO REDO, BLOCK THE BUTTON IF NONE CARS?

        self.fields['author'].queryset = User.objects.filter(id=self.request.user.id)
        self.fields['author'].initial = User.objects.get(id=self.request.user.id)
        self.fields['author'].widget = HiddenInput()

        """
        Make sure only cars made by the currently logged-in user are available.
        Make sure only cars without created car deal are available.
        """
        if self.instance and self.instance.pk:
            # Include the current Car but exclude every other Car
            self.fields['car'].queryset = Car.objects.filter(id=self.instance.car.id)
        else:
            # Exclude all cars that already have Car Deals
            self.fields['car'].queryset = user_cars.exclude(
                id__in=CarDeal.objects.values_list('car', flat=True)
            )

    # def clean_car(self):
    #     """ Make sure only one car deal can be created per car"""
    #     car = self.cleaned_data.get('car')
    #     if CarDeal.objects.filter(car=car).exists():
    #         raise ValidationError('A deal for this car already exists!')
    #     return car

    class Meta:
        model = CarDeal
        fields = '__all__'

projekt_zespolowy/cardeals/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.db.models import Count, Avg
from django.db.models.functions import ExtractYear
from django.shortcuts import render
from django.views.generic import CreateView, DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, DeleteView

from cardeals.models import Car, CarDeal
from cardeals.forms import CarForm, CarDealForm
from cardeals.filters import CarDealFilter

class CarDealListView(ListView):
    model = CarDeal
    paginate_by = 100

    context_object_name = 'deals'

    def get_queryset(self):
        return CarDealFilter(self.request.GET, queryset=super().get_queryset()).qs

class CarDealDetailView(DetailView):
    model = CarDeal

class CarCreateView(LoginRequiredMixin ,CreateView):
    model = Car
    form_class = CarForm

    def get_form_kwargs(self):
        kw = super(CarCreateView, self).get_form_kwargs()
        kw['request'] = self.request
        return kw

class CarDealCreateView(LoginRequiredMixin ,CreateView):
    model = CarDeal
    form_class = CarDealForm

    def get_form_kwargs(self):
        kw = super(CarDealCreateView, self).get_form_kwargs()
        kw['request'] = self.request
        return kw

class CarDealUpdateView(LoginRequiredMixin, UpdateView):
    model = CarDeal
    form_class = CarDealForm
    template_name = 'cardeals/cardeal_form.html'  # Używamy istniejącego szablonu formularza

    def get_form_kwargs(self):
        kw = super(CarDealUpdateView, self).get_form_kwargs()
        kw['request'] = self.request
        return kw

    def get_success_url(self):
        # Po zapisaniu użytkownik wraca do szczegółów oferty
        return self.object.get_absolute_url()

class CarDealDeleteView(LoginRequiredMixin, DeleteView):
    model = CarDeal
    success_url = reverse_lazy("cardeals:list")

class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "cardeals/dashboard.html"


class DashboardView(TemplateView):
    template_name = "cardeals/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        deals = CarDeal.objects.all()
        cars = Car.objects.all()

        # Wykres 1: Kategorie cenowe
        context['cheap'] = deals.filter(price__lt=50000).count()
        context['mid'] = deals.filter(price__gte=50000, price__lte=150000).count()
        context['expensive'] = deals.filter(price__gt=150000).count()

        # Wykres 2: Ilość samochodów dla każdej liczby drzwi
        doors_count = cars.values('number_of_doors').annotate(count=Count('id')).order_by('number_of_doors')
        context['doors_labels'] = [str(item['number_of_doors']) for item in doors_count]
        context['doors_data'] = [item['count'] for item in doors_count]

        # Wykres 3: Średnia moc (power) dla każdego condition
        power_avg = cars.values('condition').annotate(avg_power=Avg('power')).order_by('condition')
        context['power_labels'] = [item['condition'] for item in power_avg]
        context['power_data'] = [round(item['avg_power'], 1) for item in power_avg]

        # Wykres 4: Liczba sprzedanych samochodów na rok
        sales_per_year = deals.values('car__year').annotate(count=Count('id')).order_by('car__year')
        context['sales_years'] = [item['car__year'] for item in sales_per_year]
        context['sales_counts'] = [item['count'] for item in sales_per_year]

        # Wyszukiwanie aut z najmniejszym przebiegiem
        manufacturer = self.request.GET.get('manufacturer', '')
        if manufacturer:
            cars_filtered = cars.filter(manufacturer__icontains=manufacturer).order_by('odometer')[:3]
            context['filtered_cars'] = cars_filtered
        else:
            context['filtered_cars'] = None





        return context

projekt_zespolowy/cardeals/templates/cardeals/car_form.html
{% extends "base.html" %}

{% block content %}
<div class="card sporty-card">
  <h2>Add a New Car</h2> <!-- Add a title to the form -->
  <form method="post" class="car-form">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save your car!" class="submit-btn">
  </form>
</div>
{% endblock %}

projekt_zespolowy/cardeals/templates/cardeals/card.html
<div class="card mb-4 box-shadow">
  <img
      alt="Thumbnail"
      class="card-img-top"
      src="{{ cardeal.main_photo }}"
      style="height: 400px; width: 100%; display: block;">
  <div class="card-body">
    <p class="card-title text-center" style="font-weight: bold">
      <a href="{{cardeal.get_absolute_url}}">
      {{cardeal.title}}
      </a>
    </p>
    <p class="card-text">
      <p>
        <span style="float: right">{{cardeal.author}}</span>
        <span style="float: left">{{cardeal.price}} PLN</span>
      </p>
    </p>
  </div>
</div>

projekt_zespolowy/cardeals/templates/cardeals/cardeal_confirm_delete.html
{%  extends "base.html" %}

{% block content %}

<div class="container">
  <div class="card">
    <div class="card-body">
      <form method="post" class="text-center">{% csrf_token %}
        <h4> Are you sure you want to delete "{{ object }}"?</h4>
        </br>
        <input type="submit" class="btn btn-danger" value="Confirm">
      </form>
  </div>
</div>
</div>

{% endblock %}

projekt_zespolowy/cardeals/templates/cardeals/cardeal_detail.html
{% extends "base.html" %}

{% block content %}
  <style>
    .card-container {
      display: flex;
      justify-content: center;
      align-items: flex-start;
      height: auto;
      margin-top: 20px;
      padding: 0 20px;
    }

    .card {
      width: 100%;
      max-width: 500px;
      border: 2px solid #ff6a00;
      border-radius: 8px;
      box-shadow: 0 4px 8px rgba(255, 106, 0, 0.3);
      overflow: hidden;
      background-color: #111;
      text-align: center;
      padding: 16px;
      display: flex;
      flex-direction: column;
      height: auto;
      color: #f5f5f5;
    }

    .img-square-wrapper img {
      width: 100%;
      height: auto;
      max-height: 300px;
      object-fit: cover;
      border-radius: 8px;
      border-bottom: 3px solid #ff6a00;
    }

    .card-title {
      font-size: 1.5rem;
      margin: 16px 0;
      color: #ff6a00;
      text-transform: uppercase;
    }

    p {
      margin: 8px 0;
    }

    span {
      display: block;
      text-align: left;
      font-size: 1rem;
      font-weight: 500;
      color: #e67e22;
    }

    .description {
      min-height: 200px;
      max-height: 200px;
      overflow-y: auto;
      text-align: left;
      -ms-overflow-style: none;
      scrollbar-width: none;
      color: #f5f5f5;
      padding: 10px;
      border: 1px solid #ff6a00;
      border-radius: 5px;
      background-color: #222;
    }

    .description::-webkit-scrollbar {
      display: none;
    }

    .edit-button {
      display: inline-block;
      padding: 8px 16px;
      font-size: 0.875rem;
      border: 2px solid #ff6a00;
      border-radius: 4px;
      color: #ff6a00;
      background-color: transparent;
      text-decoration: none;
      text-align: center;
      cursor: pointer;
      transition: all 0.3s ease;
      font-weight: bold;
    }

    .edit-button:hover {
      background-color: #e65a00;
      color: white;
      border-color: #e65a00;
    }

    .delete-button {
      border-color: red;
      color: red;
    }

    .delete-button:hover {
      background-color: red;
      color: white;
    }

    .card-footer {
      background-color: #111 !important;
      border-top: none;
      padding: 8px;
      display: flex;
      justify-content: space-between;
      margin-top: 15px;
    }

    /* Media Queries */
    @media (max-width: 1200px) {
      .card-container {
        padding: 0 15px;
      }

      .card {
        max-width: 450px;
      }
    }

    @media (max-width: 1000px) {
      .card-container {
        padding: 0 10px;
      }

      .card {
        max-width: 400px;
      }
    }

    @media (max-width: 768px) {
      .card-container {
        padding: 0 5px;
      }

      .card {
        max-width: 100%;
      }

      .card-title {
        font-size: 1.2rem;
      }

      .edit-button {
        font-size: 0.75rem;
        padding: 6px 12px;
      }
    }
  </style>

  <div class="card-container">
    <div class="card">
      <div class="img-square-wrapper">
        <img alt="Thumbnail" src="{{ cardeal.main_photo }}">
      </div>
      <h3 class="card-title">{{ cardeal.title }}</h3>
      <p>
        <span><strong>Owner:</strong> {{ cardeal.author }}</span>
        <span><strong>Contact:</strong> {{ cardeal.contact }}</span>
        <span><strong>Price:</strong> {{ cardeal.price }} PLN</span>
      </p>

      <p class="description">{{ cardeal.description }}</p>

      {% if request.user.is_authenticated and request.user.id == cardeal.author_id %}
      <div class="card-footer">
        <a href="{% url 'cardeals:editcardeal' cardeal.slug %}" class="btn edit-button">
          ✏️ Edit
        </a>
        <a href="{% url 'cardeals:deletecardeal' cardeal.slug %}" class="btn edit-button delete-button">
          ❌ Delete
        </a>
      </div>
      {%  endif %}
    </div>
  </div>
{% endblock %}

projekt_zespolowy/cardeals/templates/cardeals/cardeal_form.html
{% extends "base.html" %}

{% block content %}
<style>
  /* Poprawka: Osobny kontener dla formularza */
  .form-container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 80vh;
  }

  .card {
    width: 100%;
    max-width: 600px;
    background: linear-gradient(135deg, #2c2c2c, #1f1f1f);
    border-radius: 8px;
    box-shadow: 0 6px 12px rgba(0, 0, 0, 0.2);
    padding: 30px;
    color: #f8f8f8;
  }

  .form-group {
    margin-bottom: 20px;
  }

  input[type="submit"] {
    width: 100%;
    padding: 12px;
    font-size: 16px;
    background-color: #ff6a00;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    transition: background-color 0.3s ease, transform 0.2s ease;
  }

  input[type="submit"]:hover {
    background-color: #e65a00;
    transform: translateY(-2px);
  }

  input[type="submit"]:focus {
    outline: none;
  }
</style>

<!-- Navbar będzie wczytany z base.html -->

<!-- Osobny kontener dla formularza -->
<div class="form-container">
  <div class="card">
    <form method="post">
      {% csrf_token %}
      <div class="form-group">
        {{ form.as_p }}
      </div>
      <input type="submit" value="Save your car!">
    </form>
  </div>
</div>

{% endblock %}

projekt_zespolowy/cardeals/templates/cardeals/cardeal_list.html
{% extends "base.html" %}

{% block content %}
<style>
  /* Kontener na karty - siatka 2 kolumny */
  .cards-container {
    display: grid;
    grid-template-columns: repeat(2, 1fr); /* TYLKO 2 KOLUMNY */
    gap: 40px; /* Większy odstęp */
    padding: 20px;
    justify-content: center;
  }

  .card {
    max-width: 90%;
    width: 90%;
    border: 1px solid #ff6a00;
    border-radius: 8px;
    box-shadow: 0 4px 8px rgba(255, 106, 0, 0.3);
    overflow: hidden;
    background-color: #111;
    text-align: center;
    padding: 16px;
    color: #f5f5f5;
  }

  .card img {
    display: block;
    width: 100%;
    height: auto;
    object-fit: cover;
    border-radius: 8px;
    border-bottom: 3px solid #ff6a00;
  }

  .card > div:first-child {
    display: contents;
  }

  /* Nagłówek */
  .card-title {
    font-size: 1.2rem;
    font-weight: bold;
    margin-top: 10px;
    color: #ff6a00;
  }

  /* Autor i cena */
  .card-footer {
    display: flex;
    justify-content: space-between;
    font-size: 14px;
    color: #e67e22;
    margin-top: 10px;
  }

  /* Nowe przyciski */
  .button-container {
    display: flex;
    justify-content: center;
    gap: 15px;
    margin-top: 20px;
  }

  .btn-custom {
    background-color: #ff6a00;
    color: white;
    padding: 12px 20px;
    border-radius: 8px;
    text-decoration: none;
    font-weight: bold;
    transition: 0.3s;
    display: inline-block;
    border: 2px solid transparent;
  }

  .btn-custom:hover {
    background-color: #e65a00;
    transform: scale(1.05);
  }

  .btn-disabled {
    background-color: #555;
    cursor: not-allowed;
    border: 2px solid #888;
  }

  .btn-disabled:hover {
    transform: none;
    background-color: #555;
  }

  .search-bar {
    display: flex;
    flex-direction: column;
    align-items: center;
    margin-top: 10px;
    color: white;
  }

  .search-bar h4 {
    color: #ff6a00;
  }

  .search-bar input {
    width: 60%;
    padding: 10px;
    border: 2px solid #ff6a00;
    border-radius: 6px;
    background-color: #222;
    color: #fff;
    transition: all 0.3s ease;
  }

  .search-bar input:focus {
    border-color: #e65a00;
    background-color: #333;
  }
</style>

<!-- Nowe przyciski -->
{% if request.user.is_authenticated %}
  <div class="button-container">
    <a href="{% url 'cardeals:createcar' %}" class="btn-custom">
      ➕ Create Car
    </a>
    {% if request.user.car_set.exists %}
      <a href="{% url 'cardeals:createcardeal' %}" class="btn-custom">
        🚗 Create Car Deal
      </a>
    {% else %}
      <span class="btn-custom btn-disabled" onclick="alert('Please create a car before trying to create a car deal!')">
        🚗 Create Car Deal
      </span>
    {% endif %}
  </div>
{% endif %}

<!-- SEARCH BAR -->
<div class="search-bar">
  <h4>Looking for something specific?</h4>
  <form method="GET">
    <input aria-label="Search" class="form-control" name="search" placeholder="Search.." type="search">
  </form>
</div>

<!-- Siatka z kartami -->
<div class="cards-container">
  {% for cardeal in deals %}
    <div class="card">
      {% include "cardeals/card.html" with cardeal=cardeal %}
    </div>
  {% endfor %}
</div>

{% endblock %}